version: '3.4'

services:
  sql-data:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flights
    ports:
      - "5433:5432"
    volumes:
      - flights-sqldata:/var/opt/npgsql
  booking-data:
    ports:
      - "6379:6379"
  flight.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - urls__grpcBookingService=http://booking.api:81      
      - ConnectionString=Host=sql-data;Database=flights;Username=admin;Password=admin
    ports:
      - "6003:80"      
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  booking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RedisConnectionString=booking-data
      - ConnectionString=Host=sql-data;Database=flights;Username=admin;Password=admin
      - PORT=80
      - GRPC_PORT=81
    ports:
      - "6001:80"
      - "6002:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  flights-sqldata:
    external: false